"""Preventive avoidance -- the self-healing half of the system.

Impact analysis alone is alerting. This module queries the graph *in reverse*
to find concrete ways to not have the problem:

  1. Alternate supplier      (EINA/EINE) -- who else is approved to supply this?
  2. Cross-plant stock        (MARD)      -- is there spare stock anywhere else?
  3. Production re-sequencing (AFKO/RESB) -- can we defer an order that has no
                                             customer commitment and reallocate
                                             its material to one that does?

For each short material the engine gathers every feasible option, then
allocates the shortfall greedily by *marginal cost per unit covered*. Free
moves (re-sequencing) are taken first by construction; beyond that, moving
stock and buying stock compete on price rather than on a fixed hierarchy, so
the plan is the cheapest feasible coverage rather than a rule of thumb.

Each action carries its cost, the exposure it removes, and the SAP records that
prove it is feasible. Nothing here is generated by an LLM.
"""

from __future__ import annotations

from collections import defaultdict

from app.graph.adapter import GraphBackend
from app.models import (
    AvoidanceAction,
    AvoidancePlan,
    FinancialExposure,
    RejectedOption,
    TraversalResult,
)

# Commercial inputs with no SAP field behind them. Every one is surfaced on the
# plan as an assumption, for the same reason the financial engine surfaces idle
# plant cost: a figure the user cannot audit is a figure they cannot defend.
EXPEDITE_FEE_PER_ORDER = 2_500.0     # rush-order administration + freight
TRANSFER_HANDLING_RATE = 0.02        # 2% of goods value to pick, pack, ship
TRANSFER_FREIGHT_FLAT = 3_500.0      # inter-plant air freight, flat

ASSUMPTION_TEXT = {
    "alternate_supplier": (
        f"Re-sourcing cost = quantity x price premium over the SAP info-record "
        f"price (EINE.NETPR vs MARA unit cost), plus a "
        f"{EXPEDITE_FEE_PER_ORDER:,.0f} rush-order fee per purchase order. The "
        f"rush fee is a commercial input, not an SAP field."
    ),
    "cross_plant_transfer": (
        f"Transfer cost = {TRANSFER_HANDLING_RATE:.0%} of goods value to pick, "
        f"pack and ship, plus {TRANSFER_FREIGHT_FLAT:,.0f} flat inter-plant "
        f"freight. Both are commercial inputs, not SAP fields."
    ),
    "production_resequence": (
        "Deferring an order with no customer commitment in the horizon is "
        "costed at zero: it consumes no purchase and incurs no penalty. It does "
        "assume the deferred output is not needed beyond the horizon."
    ),
}


def attribute_exposure(
    traversal: TraversalResult, exposure: FinancialExposure
) -> dict[tuple[str, str], float]:
    """Split total exposure across the materials that cause it.

    Needed so an action that fixes one material can claim a defensible share of
    the risk rather than the whole headline number.
    """
    # Downstream value carried by each halted production order.
    order_value: dict[str, float] = {}
    penalty_by_matnr: dict[str, float] = defaultdict(float)
    so_by_matnr: dict[str, float] = defaultdict(float)

    for so in traversal.sales_orders:
        so_by_matnr[so.matnr] += so.net_value
    so_matnr = {so.vbeln: so.matnr for so in traversal.sales_orders}
    for dv in traversal.deliveries:
        m = so_matnr.get(dv.ref_sales_order)
        if m:
            penalty_by_matnr[m] += dv.penalty_amount

    for apo in traversal.production_orders:
        order_value[apo.aufnr] = (
            so_by_matnr.get(apo.output_matnr, 0.0)
            + penalty_by_matnr.get(apo.output_matnr, 0.0)
        )

    attrib: dict[tuple[str, str], float] = defaultdict(float)
    for apo in traversal.production_orders:
        blockers = apo.blocking_materials or []
        if not blockers:
            continue
        share = order_value.get(apo.aufnr, 0.0) / len(blockers)
        for matnr in blockers:
            attrib[(matnr, apo.werks)] += share

    # Stranded PO value attaches to its own material/plant.
    short_keys = {(m.matnr, m.werks) for m in traversal.materials if m.shortfall_qty > 0}
    for po in traversal.purchase_orders:
        if (po.matnr, po.werks) in short_keys:
            attrib[(po.matnr, po.werks)] += po.net_value

    # Plant halt cost splits across the materials blocking that plant.
    halt_plants: dict[str, set[str]] = defaultdict(set)
    for apo in traversal.production_orders:
        for matnr in apo.blocking_materials:
            halt_plants[apo.werks].add(matnr)
    if traversal.production_orders and exposure.production_halt_cost:
        per_plant = exposure.production_halt_cost / max(1, len(halt_plants))
        for werks, mats in halt_plants.items():
            for matnr in mats:
                attrib[(matnr, werks)] += per_plant / max(1, len(mats))

    return dict(attrib)


def _candidates(backend, traversal, m, committed_outputs):
    """Every feasible way to cover a shortfall on one material at one plant.

    Each candidate is (kind, qty_available, cost_of(qty), builder). Cost is a
    function of quantity because flat fees make per-unit cost depend on how
    much of the shortfall the option ends up covering.
    """
    out = []

    # -- free: defer an order that has no customer waiting on it ----------
    for apo in traversal.production_orders:
        if apo.werks != m.werks or m.matnr not in apo.blocking_materials:
            continue
        if apo.output_matnr in committed_outputs:
            continue  # a customer is waiting on this order; do not defer it
        released = sum(
            r["BDMNG"] for r in backend.reservations_of_order(apo.aufnr)
            if r["MATNR"] == m.matnr
        )
        if released <= 0:
            continue
        out.append((
            "production_resequence", released, (lambda q: 0.0),
            {"aufnr": apo.aufnr, "output": apo.output_matnr,
             "output_name": apo.output_material_name, "released": released},
        ))

    # -- move stock we already own from another plant ---------------------
    for other in backend.stock_all_plants(m.matnr):
        if other["WERKS"] == m.werks:
            continue
        local_demand = sum(
            r["BDMNG"] for r in backend.reservations_for(m.matnr, other["WERKS"])
        )
        spare = min(other["LABST"] - other["EISBE"], other["LABST"] - local_demand)
        if spare <= 0:
            continue
        plant = backend.plant(other["WERKS"]) or {}
        out.append((
            "cross_plant_transfer", spare,
            (lambda q, uc=m.unit_cost: q * uc * TRANSFER_HANDLING_RATE + TRANSFER_FREIGHT_FLAT),
            {"werks": other["WERKS"], "plant_name": plant.get("NAME1", other["WERKS"]),
             "labst": other["LABST"], "eisbe": other["EISBE"],
             "local_demand": local_demand, "spare": spare},
        ))

    # -- buy from an approved alternate source ----------------------------
    for alt in backend.alternate_sources(m.matnr, traversal.supplier_id):
        if alt["APLFZ"] >= traversal.delay_days:
            continue  # cannot beat the delayed arrival, so it solves nothing
        premium = max(0.0, alt["NETPR"] - m.unit_cost)
        out.append((
            "alternate_supplier", float("inf"),
            (lambda q, pr=premium: q * pr + EXPEDITE_FEE_PER_ORDER),
            {"alt": alt, "premium": premium},
        ))

    return out


def _candidate_summary(kind, meta, m, qty) -> str:
    if kind == "production_resequence":
        return f"Defer order {meta['aufnr']} to release {qty:,.0f} x {m.matnr}"
    if kind == "cross_plant_transfer":
        return f"Transfer {qty:,.0f} x {m.matnr} from plant {meta['werks']}"
    return f"Re-source {qty:,.0f} x {m.matnr} from {meta['alt']['supplier_name']}"


def _build_action(kind, qty, cost, meta, m, traversal, claim):
    """Turn an allocated candidate into a reportable action."""
    if kind == "production_resequence":
        return AvoidanceAction(
            kind=kind,
            title=f"Defer production order {meta['aufnr']} ({meta['output']})",
            description=(
                f"{meta['output_name']} has no customer commitment inside the impact "
                f"horizon. Deferring order {meta['aufnr']} releases "
                f"{meta['released']:,.0f} units of {m.matnr} to orders that do have "
                f"customer commitments. No purchase cost."
            ),
            target_matnr=m.matnr, target_material_name=m.material_name,
            target_werks=m.werks, qty_covered=qty, lead_time_days=0.0,
            cost=0.0, risk_mitigated=round(claim(qty), 2),
            sap_source="AFKO/AFPO/RESB",
            evidence=[
                f"AFKO.AUFNR={meta['aufnr']} produces {meta['output']}",
                f"No VBAP line demands {meta['output']} in the impact set",
                f"RESB.BDMNG={meta['released']:,.0f} of {m.matnr} released",
            ],
        )
    if kind == "cross_plant_transfer":
        return AvoidanceAction(
            kind=kind,
            title=f"Transfer {qty:,.0f} x {m.matnr} from plant {meta['werks']}",
            description=(
                f"{meta['plant_name']} holds {meta['labst']:,.0f} units against "
                f"{meta['eisbe']:,.0f} safety stock and {meta['local_demand']:,.0f} local "
                f"demand, leaving {meta['spare']:,.0f} transferable. Covers {qty:,.0f} of "
                f"the {m.shortfall_qty:,.0f}-unit shortfall at plant {m.werks}."
            ),
            target_matnr=m.matnr, target_material_name=m.material_name,
            target_werks=m.werks, qty_covered=qty, lead_time_days=2.0,
            cost=round(cost, 2), risk_mitigated=round(claim(qty), 2),
            sap_source="MARD/MARC",
            evidence=[
                f"MARD.LABST={meta['labst']:,.0f} at WERKS={meta['werks']}",
                f"MARC.EISBE={meta['eisbe']:,.0f} safety stock retained",
                f"RESB local demand at {meta['werks']} = {meta['local_demand']:,.0f}",
            ],
        )
    alt = meta["alt"]
    pct = (meta["premium"] / m.unit_cost * 100) if m.unit_cost else 0.0
    return AvoidanceAction(
        kind=kind,
        title=f"Re-source {qty:,.0f} x {m.matnr} from {alt['supplier_name']}",
        description=(
            f"{alt['supplier_name']} is an approved source for {m.matnr} with a "
            f"{alt['APLFZ']}-day lead time, against a {traversal.delay_days}-day delay. "
            f"Unit price {alt['NETPR']:,.2f} vs {m.unit_cost:,.2f} ({pct:+.1f}%), plus a "
            f"{EXPEDITE_FEE_PER_ORDER:,.0f} expedite fee."
        ),
        target_matnr=m.matnr, target_material_name=m.material_name,
        target_werks=m.werks, qty_covered=qty,
        lead_time_days=float(alt["APLFZ"]),
        cost=round(cost, 2), risk_mitigated=round(claim(qty), 2),
        sap_source="EINA/EINE",
        evidence=[
            f"EINA/EINE: LIFNR={alt['LIFNR']} approved for MATNR={m.matnr}",
            f"EINE.APLFZ={alt['APLFZ']}d < delay {traversal.delay_days}d",
            f"EINE.NETPR={alt['NETPR']:,.2f} vs MARA unit cost {m.unit_cost:,.2f}",
            f"LFA1.risk_score={alt['risk_score']:.2f}",
        ],
    )


def find_actions(
    backend: GraphBackend,
    traversal: TraversalResult,
    exposure: FinancialExposure,
) -> AvoidancePlan:
    attrib = attribute_exposure(traversal, exposure)
    actions: list[AvoidanceAction] = []
    rejected: list[RejectedOption] = []

    shortfalls = [m for m in traversal.materials if m.shortfall_qty > 0]
    shortfalls.sort(key=lambda m: -attrib.get((m.matnr, m.werks), 0.0))

    committed_outputs = {so.matnr for so in traversal.sales_orders}
    # An order deferred to free material A must not be "deferred" again for
    # material B as if it were a second, independent action.
    deferred_orders: set[str] = set()

    for m in shortfalls:
        material_exposure = attrib.get((m.matnr, m.werks), 0.0)
        remaining = m.shortfall_qty
        if material_exposure <= 0 or remaining <= 0:
            continue

        def claim(qty: float, _m=m, _exp=material_exposure) -> float:
            return _exp * (min(qty, _m.shortfall_qty) / _m.shortfall_qty)

        pool = _candidates(backend, traversal, m, committed_outputs)

        while remaining > 0 and pool:
            best, best_rate, best_qty, best_cost = None, None, 0.0, 0.0
            for cand in pool:
                kind, avail, cost_of, meta = cand
                if kind == "production_resequence" and meta["aufnr"] in deferred_orders:
                    continue
                qty = remaining if avail == float("inf") else min(avail, remaining)
                if qty <= 0:
                    continue
                cost = cost_of(qty)
                rate = cost / qty
                if best_rate is None or rate < best_rate:
                    best, best_rate, best_qty, best_cost = cand, rate, qty, cost
            if best is None:
                break

            kind, _avail, _cost_of, meta = best
            # Everything else in the pool lost on price this round; record the
            # runners-up so the decision is inspectable, not just asserted.
            for cand in pool:
                if cand is best:
                    continue
                c_kind, c_avail, c_cost_of, c_meta = cand
                c_qty = remaining if c_avail == float("inf") else min(c_avail, remaining)
                if c_qty <= 0:
                    continue
                c_rate = c_cost_of(c_qty) / c_qty
                if c_rate <= best_rate:
                    continue
                rejected.append(RejectedOption(
                    kind=c_kind,
                    summary=_candidate_summary(c_kind, c_meta, m, c_qty),
                    unit_cost=round(c_rate, 2),
                    reason=(
                        f"A zero-cost option covered the same {m.matnr} shortfall; "
                        f"this would have cost {c_rate:,.2f}/unit."
                        if best_rate == 0
                        else f"{c_rate:,.2f}/unit against {best_rate:,.2f}/unit for the "
                             f"option taken, for the same {m.matnr} shortfall."
                    ),
                ))
            actions.append(_build_action(kind, best_qty, best_cost, meta, m, traversal, claim))
            if kind == "production_resequence":
                deferred_orders.add(meta["aufnr"])
            pool.remove(best)
            remaining -= best_qty

    # An option rejected in one allocation round but chosen in a later one is
    # not a rejection; and the same losing option can lose several rounds.
    chosen = {(a.kind, a.target_matnr, a.target_werks) for a in actions}
    seen: set[str] = set()
    deduped: list[RejectedOption] = []
    for r in rejected:
        if r.summary in seen:
            continue
        seen.add(r.summary)
        deduped.append(r)
    rejected = [
        r for r in deduped
        if not any(r.kind == k and r.summary.endswith(w) for k, _mt, w in
                   ((c[0], c[1], c[2]) for c in chosen))
        or r.kind not in {c[0] for c in chosen}
    ]
    rejected = [r for r in deduped if r.kind not in {c[0] for c in chosen}]

    actions.sort(key=lambda a: (-a.risk_mitigated, a.cost))

    total_cost = sum(a.cost for a in actions)
    total_mitigated = sum(a.risk_mitigated for a in actions)
    before = exposure.total_financial_exposure
    after = max(0.0, before - total_mitigated)

    # Declare only the inputs the chosen actions actually used.
    assumptions = [
        ASSUMPTION_TEXT[kind]
        for kind in ("alternate_supplier", "cross_plant_transfer", "production_resequence")
        if any(a.kind == kind for a in actions)
    ]
    if actions:
        assumptions.append(
            "Risk mitigated per action is that material's share of total exposure, "
            "scaled by the fraction of its shortfall the action covers."
        )

    return AvoidancePlan(
        actions=actions,
        considered_but_rejected=rejected,
        assumptions=assumptions,
        exposure_before=round(before, 2),
        exposure_after=round(after, 2),
        total_avoidance_cost=round(total_cost, 2),
        total_risk_mitigated=round(total_mitigated, 2),
    )
